// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fpajmowdardbslmchqun.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZwYWptb3dkYXJkYnNsbWNocXVuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzMzA5NjgsImV4cCI6MjA2OTkwNjk2OH0.wLXKMr-gym-oiB61cOQ0xS6DSkGBzzFv9oPB4SnImEc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});